stages:
  data_ingestion:
    cmd: python -m src.data_ingestion
    deps:
      - src/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion.dataset_path
    outs:
      - artifacts/raw/images.npy
      - artifacts/raw/labels.npy
  data_preprocessing:
    cmd: python -m src.data_preprocessing
    deps:
      - src/data_preprocessing.py
      - artifacts/raw/images.npy
      - artifacts/raw/labels.npy
      - params.yaml
    outs:
      - artifacts/processed/X_train.npy
      - artifacts/processed/X_val.npy
      - artifacts/processed/y_train.npy
      - artifacts/processed/y_val.npy
  model_training:
    cmd: python -m src.model_training
    deps:
      - src/model_training.py
      - artifacts\processed\X_train.npy
      - artifacts\processed\y_train.npy
      - params.yaml
    outs:
      - artifacts\models\fraud_detector.pt