stages:
  data_ingestion:
    cmd: python -m src.data_ingestion
    deps:
      - src/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion.dataset_path
    outs:
      - artifacts/raw/images.npy
      - artifacts/raw/labels.npy