data_ingestion:
  dataset_path: "C:/Users/Arun/Downloads/archive/casia/CASIA2"
  raw_data_path: "data/raw/"

artifacts:
  raw_data: "artifacts/raw/"
  processed_data: "artifacts/processed/"
  models: "artifacts/models/"
  results: "artifacts/results/"

training:
  epochs: 30
  batch_size: 128
  learning_rate: 0.001